
name: Deploy RG

on:
  workflow_dispatch:
    

permissions:
  id-token: write
  contents: read



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        


    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        az account show
        az group list



    #  run: |
    #    echo "${{ steps.fa.outputs.app-url }}"

    - name: Azure logout
      run: |
        az logout
